In [2]:
# Show ALL outputs in cell, not only last result
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
relative_filepath = "../../"

In [4]:
# Set relative path mapping for module imports
import sys

sys.path.append(relative_filepath)

#for path in sys.path:
#    print(path)

In [5]:
# External Dependencies
import numpy as np
import pandas as pd

In [6]:
# Read in pickled combined data
X_y_data = pd.read_pickle(relative_filepath + "data/interim/X_y_data.pkl")
X_combined = pd.read_pickle(relative_filepath + "data/interim/X_combined.pkl")
y_combined = pd.read_pickle(relative_filepath + "data/interim/y_combined.pkl")

# Read in pickled train data
X_y_train = pd.read_pickle(relative_filepath + "data/interim/X_y_train.pkl")
X_train = pd.read_pickle(relative_filepath + "data/interim/X_train.pkl")
y_train = pd.read_pickle(relative_filepath + "data/interim/y_train.pkl")

# Read in pickled test data
X_y_test = pd.read_pickle(relative_filepath + "data/interim/X_y_test.pkl")
X_test = pd.read_pickle(relative_filepath + "data/interim/X_test.pkl")
y_test = pd.read_pickle(relative_filepath + "data/interim/y_test.pkl")

In [7]:
# Recap data structure
X_y_data.head()
X_y_data.shape

target = "classLabel"

input_dfs = [X_y_data,
             X_combined,
             X_y_train,
             X_train,
             X_y_test,
             X_test]

v1     v2         v3 v4                  v5                 v6     v7 v8 v9  \
0  a  17,92    5,4e-05  u  -0,840182024985552  0,522882590622095   1,75  f  t   
1  b  16,92   3,35e-05  y   -2,15963506605476  0,774187133555115   0,29  f  f   
2  b  31,25  0,0001125  u    1,75068668089807   0,76036270650308      0  f  t   
3  a  48,17  0,0001335  u    4,17487068567425  0,888963139486792  0,335  f  f   
4  b  32,33    0,00035  u   -3,78547915257514  0,489023844085239    0,5  f  f   

   v10 v11 v12    v13  v14       v15  v16  v17 classLabel  
0    1   t   g   80.0    5    800000    t    0        no.  
1    0   f   s  200.0    0     2e+06  NaN    0        no.  
2    1   f   g   96.0   19    960000    t    0        no.  
3    0   f   g    0.0  120         0  NaN    0        no.  
4    0   t   g  232.0    0  2.32e+06    f    0        no.

(3900, 18)

## d) Initial Data Preprocessing

#### i) Encode target variable

In [8]:
from sklearn import preprocessing

le = preprocessing.LabelEncoder()
le.fit(X_y_train[target])

list(le.classes_)
list(le.inverse_transform([0, 1]))

X_y_data[target] = le.transform(X_y_data[target])
y_combined = le.transform(y_combined)

X_y_train[target] = le.transform(X_y_train[target])
y_train = le.transform(y_train)

X_y_test[target] = le.transform(X_y_test[target])
y_test = le.transform(y_test)

LabelEncoder()

['no.', 'yes.']

['no.', 'yes.']

In [9]:
#for df in input_dfs: 
#    df.head()
#    df.shape

# Check newly encoded target
print("### COMBINED ###")
X_y_data.head()
X_y_data.shape

y_combined
y_combined.shape

print("### TRAIN ###")
X_y_train.head()
X_y_train.shape

y_train
y_train.shape

print("### TEST ###")
X_y_test.head()
X_y_test.shape

y_test
y_test.shape

### COMBINED ###


v1     v2         v3 v4                  v5                 v6     v7 v8 v9  \
0  a  17,92    5,4e-05  u  -0,840182024985552  0,522882590622095   1,75  f  t   
1  b  16,92   3,35e-05  y   -2,15963506605476  0,774187133555115   0,29  f  f   
2  b  31,25  0,0001125  u    1,75068668089807   0,76036270650308      0  f  t   
3  a  48,17  0,0001335  u    4,17487068567425  0,888963139486792  0,335  f  f   
4  b  32,33    0,00035  u   -3,78547915257514  0,489023844085239    0,5  f  f   

   v10 v11 v12    v13  v14       v15  v16  v17  classLabel  
0    1   t   g   80.0    5    800000    t    0           0  
1    0   f   s  200.0    0     2e+06  NaN    0           0  
2    1   f   g   96.0   19    960000    t    0           0  
3    0   f   g    0.0  120         0  NaN    0           0  
4    0   t   g  232.0    0  2.32e+06    f    0           0

(3900, 18)

array([0, 0, 0, ..., 1, 1, 1])

(3900,)

### TRAIN ###


v1     v2         v3 v4                  v5                 v6     v7 v8 v9  \
0  a  17,92    5,4e-05  u  -0,840182024985552  0,522882590622095   1,75  f  t   
1  b  16,92   3,35e-05  y   -2,15963506605476  0,774187133555115   0,29  f  f   
2  b  31,25  0,0001125  u    1,75068668089807   0,76036270650308      0  f  t   
3  a  48,17  0,0001335  u    4,17487068567425  0,888963139486792  0,335  f  f   
4  b  32,33    0,00035  u   -3,78547915257514  0,489023844085239    0,5  f  f   

   v10 v11 v12    v13  v14        v15  v16  v17  classLabel  
0    1   t   g   80.0    5   800000.0    t    0           0  
1    0   f   s  200.0    0  2000000.0  NaN    0           0  
2    1   f   g   96.0   19   960000.0    t    0           0  
3    0   f   g    0.0  120        0.0  NaN    0           0  
4    0   t   g  232.0    0  2320000.0    f    0           0

(3700, 18)

array([0, 0, 0, ..., 1, 1, 1])

(3700,)

### TEST ###


v1     v2         v3 v4            v5           v6     v7 v8 v9  v10 v11  \
0  b  32,33    0,00075  u   0,840107307  0,544982291  1,585  t  f    0   t   
1  b  23,58   0,000179  u  -4,174395711  0,864361709   0,54  f  f    0   t   
2  b  36,42   7,50E-05  y    2,23222567  0,627475551  0,585  f  f    0   f   
3  b  18,42  0,0010415  y  -2,469969629  0,846741022  0,125  t  f    0   f   
4  b   24,5  0,0013335  y  -3,149422333  0,321087006   0,04  f  f    0   t   

  v12    v13  v14      v15  v16  v17  classLabel  
0   s  420.0    0  4200000  NaN    1           0  
1   g  136.0    1  1360000  NaN    0           0  
2   g  240.0    3  2400000  NaN    1           0  
3   g  120.0  375  1200000  NaN    0           0  
4   g  120.0  475  1200000    f    1           0

(200, 18)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1])

(200,)

In [10]:
"Combined Features & Target: X_y_data Type", type(X_y_data)
"Combined Target: y_combined Type", type(y_combined)

"Train Features & Target: X_y_train Type", type(X_y_train)
"Train Target: y_train Type", type(y_train)

"Test Features & Target: X_y_test Type", type(X_y_test)
"Test Target: y_test Type", type(y_test)

('Combined Features & Target: X_y_data Type', pandas.core.frame.DataFrame)

('Combined Target: y_combined Type', numpy.ndarray)

('Train Features & Target: X_y_train Type', pandas.core.frame.DataFrame)

('Train Target: y_train Type', numpy.ndarray)

('Test Features & Target: X_y_test Type', pandas.core.frame.DataFrame)

('Test Target: y_test Type', numpy.ndarray)

#### ii) Check data types of observations in all datasets

In [31]:
print("### COMBINED ###")
X_y_data.dtypes
print("### TRAIN ###")
X_y_train.dtypes
print("### TEST ###")
X_y_test.dtypes
print("### COMPARE TRAIN VS TEST ###")
X_y_train.dtypes == X_y_test.dtypes

### COMBINED ###


v1             object
v2             object
v3             object
v4             object
v5             object
v6             object
v7             object
v8             object
v9             object
v10             int64
v11            object
v12            object
v13           float64
v14             int64
v15            object
v16            object
v17             int64
classLabel      int64
dtype: object

### TRAIN ###


v1             object
v2             object
v3             object
v4             object
v5             object
v6             object
v7             object
v8             object
v9             object
v10             int64
v11            object
v12            object
v13           float64
v14             int64
v15           float64
v16            object
v17             int64
classLabel      int64
dtype: object

### TEST ###


v1             object
v2             object
v3             object
v4             object
v5             object
v6             object
v7             object
v8             object
v9             object
v10             int64
v11            object
v12            object
v13           float64
v14             int64
v15            object
v16            object
v17             int64
classLabel      int64
dtype: object

### COMPARE TRAIN VS TEST ###


v1             True
v2             True
v3             True
v4             True
v5             True
v6             True
v7             True
v8             True
v9             True
v10            True
v11            True
v12            True
v13            True
v14            True
v15           False
v16            True
v17            True
classLabel     True
dtype: bool

### iii) Actions from first inspection

In [ ]:
# Convert comma floats to point floats
conversion_cols = ['v2', 'v3', 'v5', 'v6', 'v7', 'v15']

for df in input_dfs:
    for col in conversion_cols: 
    
        df[col] = df[conversion_cols].apply(lambda x: pd.to_numeric(x.astype(str)
                                                                     .str.replace(',','.'),
                                                                     errors='coerce'))

In [ ]:
#for df in input_dfs: 
#    df.drop(df.columns[df.columns.str.contains('v15')], 1, inplace=True)

## f) Re-Save Updated Datasets

In [ ]:
# Pickle combined set
X_y_data.to_pickle(relative_filepath + "data/interim/X_y_data.pkl")
X_combined.to_pickle(relative_filepath + "data/interim/X_combined.pkl")
y_combined.to_pickle(relative_filepath + "data/interim/y_combined.pkl")

# Pickle training set
X_y_train.to_pickle(relative_filepath + "data/interim/X_y_train.pkl")
X_train.to_pickle(relative_filepath + "data/interim/X_train.pkl")
y_train.to_pickle(relative_filepath + "data/interim/y_train.pkl")

# Pickle test set
X_y_test.to_pickle(relative_filepath + "data/interim/X_y_test.pkl")
X_test.to_pickle(relative_filepath + "data/interim/X_test.pkl")
y_test.to_pickle(relative_filepath + "data/interim/y_test.pkl")